# fly.toml app configuration file generated for bynogame-price-analyst-consumer on 2023-10-02T19:32:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bynogame-price-analyst-consumer"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
